
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "37a6468064f6d44bc36b44ae7513e5b35164bf6b",
 "version": "1.16.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
