
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-30T20:37:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f01a397ddcded8b53e8d3fad9c481fa61a4fba0",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
